# fly.toml app configuration file generated for server-autumn-water-8460 on 2024-09-03T11:24:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-autumn-water-8460'
primary_region = 'ewr'



[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']
  protocol = "tcp"
    
  [[services.ports]]
    handlers = ["http"]
    port = 3000
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
